name: Deploy to Docker Swarm

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          welford/uvdesk:latest
          ghcr.io/welford/uvdesk:latest
        push: ${{ github.ref == 'refs/heads/master' }}
    
    - name: Deploy to Docker Swarm
      uses: dtzar/docker-swarm-action@v1
      with:
        host: ${{ secrets.SWARM_HOST }}
        username: ${{ secrets.SWARM_USERNAME }}
        password: ${{ secrets.SWARM_PASSWORD }}
        service_name: ${{ secrets.SWARM_SERVICE_NAME }}
        image: ghcr.io/welford/uvdesk:latest